### ISSUE TITLE
Incompatibility with Livesplit 1.8

### ISSUE THREAD

**Issue by SirWillian** [fatalis/SourceSplit#17]
The ISettings interface was changed in Livesplit 1.8, causing a crash. Seems like this is the only occurence of SourceSplit reading the settings

![image](https://user-images.githubusercontent.com/22877883/78847577-973c3b00-79e5-11ea-982b-a5a04012e7c5.png)

**Comment by Parker8283** [comment]
#18 should do the trick :)

**Comment by fatalis** [comment]
@Parker8283 Thanks, will push a release tomorrow.

**Comment by Parker8283** [comment]
This can probably be closed now.
