### ISSUE TITLE
Autosplitter wont activate

### ISSUE THREAD

**Issue by mooshiros** [fatalis/SourceSplit#22]
When I try activating the autosplitter, it simply says that the given key was not present in the dictionary. This happens to me in portal, half life 2, and portal 2 (though I suspect that in portal w it's because I dont have sars) I haven't tried any other game. For portal and hl2 I'm on source unpack

**Comment by fatalis** [comment]
Latest version of both LiveSplit and SourceSplit?

**Comment by mooshiros** [comment]
I'm on version 1.8.14 of livesplit idk if thats the latest and I'm just using the autisplitter thats built in

**Comment by mooshiros** [comment]
So turns out I'm dumb and I just had to install it and manually put it in livesplit.
